export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const START_FETCHING_USERS = 'START_FETCHING_USERS'
export const STOP_FETCHING_USERS = 'STOP_FETCHING_USERS'

export const CHECK_USER_MODAL = 'CHECK_USER_MODAL';
export const CHECK_USER = 'CHECK_USER';

export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_CANCELED = 'CHECK_USER_CANCELED';

export const CHECK_USER_JUDICIAL_RECORDS = 'CHECK_USER_JUDICIAL_RECORDS';
export const CHECK_USER_PROSPECT_QUALIFICATION_RECORDS = 'CHECK_USER_PROSPECT_QUALIFICATION_RECORDS';
